import { OWNER_NAME, AI_NAME } from "@/config";

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-8 space-y-4">
      <h1 className="text-2xl font-bold">Terms of Use</h1>

      <p className="text-sm text-muted-foreground">
        These Terms of Use govern your access to and use of{" "}
        <strong>{AI_NAME}</strong> (the &quot;Application&quot;), an experimental
        AI project created by {OWNER_NAME} for academic and learning purposes.
        By accessing or using the Application, you agree to these Terms.
      </p>

      <h2 className="text-lg font-semibold mt-4">1. Nature of the tool</h2>
      <p className="text-sm text-muted-foreground">
        The Application is a prototype HR policy assistant designed to help
        users:
      </p>
      <ul className="text-sm text-muted-foreground list-disc pl-5 space-y-1">
        <li>Generate draft HR policies and procedures.</li>
        <li>
          Summarise and explain Indian labour-law concepts in plain language.
        </li>
        <li>Create checklists and guidance notes for internal HR use.</li>
      </ul>
      <p className="text-sm text-muted-foreground">
        It is intended solely as an <strong>educational and exploratory tool</strong> and
        is not a production system or commercial product.
      </p>

      <h2 className="text-lg font-semibold mt-4">
        2. No legal or professional advice
      </h2>
      <p className="text-sm text-muted-foreground">
        The Application and its outputs <strong>do not constitute legal advice,
        HR advice, or any other professional advice</strong>. Use of the tool does
        not create a lawyer–client, consultant–client, or employer–employee
        relationship between you and {OWNER_NAME} or any contributor.
      </p>
      <p className="text-sm text-muted-foreground">
        The Application may reference Indian labour laws and HR practices, but:
      </p>
      <ul className="text-sm text-muted-foreground list-disc pl-5 space-y-1">
        <li>It may be incomplete, outdated, or inaccurate.</li>
        <li>
          It does not track differences between central and state laws or
          industry-specific regulations in a comprehensive way.
        </li>
        <li>
          It cannot take into account the full facts, context, and risk profile
          of your organisation.
        </li>
      </ul>
      <p className="text-sm text-muted-foreground">
        You must obtain independent advice from a qualified HR professional and
        / or licensed labour lawyer before relying on any output.
      </p>

      <h2 className="text-lg font-semibold mt-4">3. User responsibility</h2>
      <p className="text-sm text-muted-foreground">
        You are solely responsible for how you use the Application and any
        decisions, documents, communications, or actions taken based on its
        responses. You agree that:
      </p>
      <ul className="text-sm text-muted-foreground list-disc pl-5 space-y-1">
        <li>
          All content generated by the Application is treated as{" "}
          <strong>draft material</strong> only.
        </li>
        <li>
          You will review, edit, and validate all outputs before using them with
          employees, regulators, or third parties.
        </li>
        <li>
          You will not rely on the Application as your sole source of
          information for compliance with Indian labour laws or any other
          regulation.
        </li>
      </ul>

      <h2 className="text-lg font-semibold mt-4">4. No liability</h2>
      <p className="text-sm text-muted-foreground">
        To the maximum extent permitted by law, {OWNER_NAME} and any
        collaborators, institutions, or service providers involved in hosting
        this project are <strong>not liable</strong> for any loss, damage,
        penalty, dispute, or cost arising from your use of the Application or
        reliance on its outputs, whether direct or indirect, foreseeable or
        unforeseeable.
      </p>

      <h2 className="text-lg font-semibold mt-4">5. Data and privacy</h2>
      <p className="text-sm text-muted-foreground">
        This academic prototype does not intentionally collect or store personal
        data beyond what is required for demonstration and testing. However, you
        should avoid entering sensitive personal information, confidential
        company data, or any information that you are not authorised to share.
      </p>

      <h2 className="text-lg font-semibold mt-4">6. Changes and availability</h2>
      <p className="text-sm text-muted-foreground">
        The Application may change, break, or be taken down at any time without
        notice. Features, prompts, and underlying models may be updated,
        replaced, or removed as part of experimentation.
      </p>

      <h2 className="text-lg font-semibold mt-4">7. Contact</h2>
      <p className="text-sm text-muted-foreground">
        If you have questions about these Terms in the context of the academic
        project, please contact the creator directly.
      </p>
    </main>
  );
}
