import Link from "next/link";
import { AI_NAME, OWNER_NAME } from "@/config";

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-8 space-y-4">
      <h1 className="text-2xl font-bold">Terms of Use</h1>
      <p className="text-sm text-muted-foreground">
        Last updated: 26 November 2025
      </p>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">About this tool</h2>
        <p>
          {AI_NAME ?? "This assistant"} (“the Assistant”) is an experimental
          AI-powered HR policy helper created for an academic capstone project
          at BITSoM. It is operated by{" "}
          {OWNER_NAME ?? "the project owner"} and is designed to help Indian
          startups and HR teams explore HR policy language and understand
          relevant concepts.
        </p>
        <p>
          The Assistant is <strong>not</strong> a law firm and does not provide
          legal, tax, or compliance advice. You are solely responsible for
          validating any outputs with a qualified professional and ensuring
          final decisions comply with applicable laws and regulations.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">No legal advice</h2>
        <p>
          All information and content generated by the Assistant is provided for
          general informational and educational purposes only. It may be
          incomplete, incorrect, or out of date, and it may not reflect the
          latest changes to Indian labour laws, state-specific rules, or your
          company’s circumstances.
        </p>
        <p>
          You must consult a qualified lawyer, company secretary, or HR
          compliance expert before adopting any policy, issuing any employee
          communication, or making employment decisions.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">Data and privacy</h2>
        <p>
          Please do not paste confidential information, trade secrets, or
          personally identifiable information (such as full Aadhaar numbers,
          salary sheets, or health details) into the chat. This project is for
          classroom evaluation only and is not designed as a production HRIS or
          legal tool.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">Limitations of use</h2>
        <p>By using this site, you agree that you will:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Use it only for exploratory, educational, or prototype testing.</li>
          <li>
            Not use it as the sole basis for hiring, firing, promotion, or
            disciplinary decisions.
          </li>
          <li>
            Take full responsibility for verifying any policy drafts or answers
            before sharing them with employees or regulators.
          </li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">Liability</h2>
        <p>
          As this is a student project, neither {OWNER_NAME ?? "the project owner"}
          , BITSoM, nor any instructor will be liable for any loss, damage, or
          consequences arising from the use of this Assistant.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">Contact</h2>
        <p>
          For questions about these terms or this project, please contact the
          project owner through the contact details provided in the course
          materials or via LinkedIn.
        </p>
      </section>

      <p className="text-sm text-muted-foreground pt-4">
        By using this site, you confirm that you understand this is an
        experimental student project and that you will not rely on it as a
        substitute for professional legal advice.
      </p>

      <p className="text-xs text-muted-foreground pt-4">
        <Link href="/" className="underline">
          ← Back to Niti HR Policy Assistant
        </Link>
      </p>
    </main>
  );
}
